server:
  tomcat:
    uri-encoding: utf-8
  port: 9080
  servlet:
    context-path: /flighty
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  datasource:
    name: flighty
    url: jdbc:mysql://127.0.0.1:3306/flighty?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl